# Pipeline Template to build MkDocs
parameters:
  - name: pythonVersion
    type: string
  - name: mkdocsSiteDir
    type: string

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.pythonVersion }}'
    inputs:
      versionSpec: '${{ parameters.pythonVersion }}'
      addToPath: true
      architecture: x64

  - script: pip install --upgrade pip wheel setuptools
    displayName: update tools

  - script: pip install -e src/mkdocs-material
    displayName: install MkDocs-Material

  - script: pip install -r src/requirements-mkdocs-material.txt
    displayName: install requirements

  - script: mkdocs build --site-dir ${{ parameters.mkdocsSiteDir }} --verbose
    displayName: build docs
