parameters:
  - name: bicepDir
    type: string
    default: $(System.DefaultWorkingDirectory)

steps:
  - task: AzureCLI@2
    name: DeployBicepFile
    displayName: Deploy Bicep file
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: ${{ parameters.bicepDir }}
      inlineScript: |
        az deployment group create \
          --name $(Build.BuildNumber) \
          --resource-group $(ResourceGroupName) \
          --template-file main.bicep \
          --parameters @main.parameters.$(sourceBranchName).json
