parameters:
  - name: bicepDir
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: resourceGroupName
    default: $(resourceGroupName)
    type: string
  - name: azureSubscription
    default: $(azureSubscription)
    type: string
  - name: location
    default: $(location)
    type: string
  - name: bicepParameter
    type: string
    default: dev

steps:
  - task: AzureCLI@2
    name: DeployBicepFile
    displayName: Deploy Bicep file
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: ${{ parameters.bicepDir }}
      inlineScript: |
        az deployment group create \
          --name $(Build.BuildNumber) \
          --resource-group ${{ parameters.ResourceGroupName }} \
          --template-file main.bicep \
          --parameters @main.parameters.${{parameters.bicepParameter}}.json
