parameters:
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)

steps:
  # - checkout: self
  #   submodules: no
  #   persistCredentials: true
  #   displayName: Checkout self

  - task: AzureCLI@2
    name: DeployBicepFile
    displayName: Deploy Bicep file
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: ${{ parameters.workingDirectory }}
      inlineScript: |
        az deployment group create \
          --name $(Build.BuildNumber) \
          --resource-group $(ResourceGroupName) \
          --template-file main.bicep \
          --parameters secretKey=$(secretKey)
    env:
      secretKey: $(secretKey)
