trigger:
  branches:
    include:
      - main
      - stable

pool:
  vmImage: ubuntu-latest

variables:
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'azure-mauwii'
  - name: env
    value: dev

stages:
  - stage:
    jobs:
      - template: azure-pipelines/jobs/bicep_jobs.yml
        parameters:
          workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/bicep'
          parameters: --parameters main.parameters.${{ variables.env }}.json
          # parameters: --parameters location=westeurope project=apwgr workerCount=1 workerSizeId=0 env=dev
