trigger:
  branches:
    include:
      - main
      - stable

variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
    readonly: true
  - ${{ if eq(variables.isMain, 'True') }}:
      - template: azure-pipelines/variables/main.yml
  - ${{ if eq(variables.isStable, 'True') }}:
      - template: azure-pipelines/variables/stable.yml
  - template: azure-pipelines/variables/default.yml

pool:
  vmImage: $(vmImageName)

stages:
  - stage:
    jobs:
      - template: azure-pipelines/jobs/bicep_jobs.yml
        parameters:
          workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/bicep'
          parameters: --parameters main.parameters.$(environment).json
