trigger:
  batch: true
  branches:
    include:
      - refs/heads/main
      - refs/heads/stable

pr: none

resources:
  repositories:
    - repository: self
      endpoint: Mauwii

parameters:
  - name: pythonVersion
    displayName: Python Version to use when building MkDocs-Material
    type: string
    values:
      - '3.6'
      - '3.8'
    default: '3.8'
  - name: mkdocsSiteDir
    displayName: Name of the Directory where MkDocs will be built to
    type: string
    default: 'site'
  - name: mkdocsDeploy
    displayName: Deploy MkDocs to GitHub-Pages
    type: boolean
    default: false
  - name: bicepDir
    displayName: Directory containing Folders with Bicep Templates
    type: string
    default: '$(bicepDir)'
  - name: bicepParameter
    displayName: Used in some templates to change Resource Name or other variables
    type: string
    values:
      - dev
      - stg
      - prod
    default: dev
  - name: resourceGroupName
    displayName: Name of the Resource Group where templates will be deployed to
    type: string
    default: '$(resourceGroupName)'
  - name: azureSubscription
    displayName: Name of the ARM-Service Connection
    type: string
    default: '$(azureSubscription)'
  - name: location
    displayName: Location where the Resources will be deployed
    type: string
    default: '$(location)'
  - name: vmImage
    displayName: Image the Build Agent should use
    type: string
    values:
      - 'ubuntu-latest'
      - 'macOS-latest'
      - 'windows-latest'
    default: 'ubuntu-latest'
  - name: agentpool
    displayName: Agent-Pool to be used
    values:
      - 'Azure Pipelines'
      - 'local'
    default: 'Azure Pipelines'
  - name: cleanup
    type: boolean
    default: true

variables:
  - template: azure-pipelines/variables/default.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: azure-pipelines/variables/${{ variables['Build.SourceBranchName'] }}.yml

extends:
  template: azure-pipelines/stages/main.yml
  parameters:
    bicepDir: ${{ parameters.bicepDir }}
    bicepParameter: ${{ parameters.bicepParameter }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    azureSubscription: ${{ parameters.azureSubscription }}
    location: ${{ parameters.location }}
    pythonVersion: ${{ parameters.pythonVersion }}
    mkdocsSiteDir: ${{ parameters.mkdocsSiteDir }}
    mkdocsDeploy: ${{ parameters.mkdocsDeploy }}
    vmImage: ${{ parameters.vmImage }}
    agentpool: ${{ parameters.agentpool }}
