trigger:
  branches:
    include:
      - main
      - stable

variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
    readonly: true
  - template: azure-pipelines/variables/default.yml
  - name: environment
    value: dev
  - ${{ if eq(variables.SourceBranchName, 'main') }}:
      - name: environment
        value: stg
  - ${{ if eq(variables.SourceBranchName, 'stable') }}:
      - name: environment
        value: prod

pool:
  vmImage: $(vmImageName)

stages:
  - stage:
    jobs:
      - template: azure-pipelines/jobs/bicep_jobs.yml
        parameters:
          workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/bicep'
          parameters: --parameters main.parameters.$(environment).json
          # parameters: --parameters location=westeurope project=apwgr workerCount=1 workerSizeId=0 env=dev
