trigger:
  batch: true
  branches:
    include:
      - refs/heads/main
      - refs/heads/stable

pr: none

variables:
  - template: azure-pipelines/variables/default.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: azure-pipelines/variables/${{ variables['Build.SourceBranchName'] }}.yml

pool:
  vmImage: $(vmImageName)

extends:
  template: azure-pipelines/main.yml
  parameters:
    mkdocsDeploy: ${{ variables['mkdocsDeploy'] }}
    bicepParameter: ${{ variables['bicepParameter'] }}
