trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'mauwii'

stages:
  - stage:
    jobs:
      - template: azure-pipelines/jobs/bicep_jobs.yml
        parameters:
          workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/bicep'
