name: 'azure-pipelines.yml'

trigger:
  batch: true
  branches:
    include:
      - refs/heads/main
      - refs/heads/stable
      - refs/pull/*
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

pr:
  - main
  - stable

variables:
  - template: azure-pipelines/variables/default.yml
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
    readonly: true

pool:
  vmImage: $(vmImageName)

stages:
  - stage: bicep
    jobs:
      - template: azure-pipelines/jobs/bicep_jobs.yml
        parameters:
          bicepDir: '$(System.DefaultWorkingDirectory)/IaC/bicep/webApp-with-insights'
          # The following parameters are have the current variable set as default value ( like this: $(<parametername>) )
          # resourceGroupName: '<Name of the ResourceGroup to use>'
          # azureSubscription: '<Name of the ARM-Service connection>'
          # location: '<location of the ResourceGroup>'

  - stage: mkdocs
    jobs:
      - template: azure-pipelines/jobs/mkdocs-material.yml
        ${{ if eq(variables.isStable, 'True') }}:
          parameters:
            mkdocsDeploy: True
