trigger:
  batch: true
  branches:
    include:
      - refs/heads/main

pr:
  - main

resources:
  repositories:
    - repository: self
      endpoint: Mauwii

variables:
  - template: azure-pipelines/variables/default.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: azure-pipelines/variables/${{ variables['Build.SourceBranchName'] }}.yml

parameters:
  - name: bicepDir
    displayName: Directory containing Folders with Bicep Templates
    type: string
    default: '$(bicepDir)'
  - name: bicepParameter
    displayName: Used in some templates to change Resource Name or other variables
    type: string
    values:
      - dev
      - stg
      - prod
    default: dev
  - name: resourceGroupName
    displayName: Name of the Resource Group where templates will be deployed to
    type: string
    default: '$(resourceGroupName)'
  - name: azureSubscription
    displayName: Name of the ARM-Service Connection
    type: string
    default: '$(azureSubscription)'
  - name: location
    displayName: Location where the Resources will be deployed
    type: string
    default: $(location)
  - name: agentpool
    displayName: Agent-Pool to be used
    values:
      - 'Azure Pipelines'
      - 'local'
    default: 'Azure Pipelines'

extends:
  template: azure-pipelines/stages/main.yml
  parameters:
    bicepDir: ${{ parameters.bicepDir }}
    bicepParameter: ${{ parameters.bicepParameter }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    azureSubscription: ${{ parameters.azureSubscription }}
    location: ${{ parameters.location }}
    agentpool: ${{ parameters.agentpool }}
