name: 'azure-pipelines.yml'

trigger:
  batch: true
  branches:
    include:
      - refs/heads/main
      - refs/heads/stable
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

pr:
  autoCancel: false
  branches:
    include:
      - main
      - stable

variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: defaultWorkingDirectory
    value: $[ variables['System.DefaultWorkingDirectory'] ]
    readonly: true
  - name: sourceDirectory
    value: $[ variables['Build.DefaultWorkingDirectory'] ]
  - template: azure-pipelines/variables/default.yml

pool:
  vmImage: $(vmImageName)

stages:
  - stage: bicep
    jobs:
      - template: azure-pipelines/jobs/bicep_jobs.yml
        parameters:
          bicepParameter: $(bicepParameter)
          bicepDir: '$[System.DefaultWorkingDirectory]/IaC/bicep/webApp-with-insights'
          # bicepDir: ${{ variables['System.DefaultWorkingDirectory'] }}/IaC/bicep/webApp-with-insights
          # bicepDir: IaC/bicep/webApp-with-insights
          # The following parameters default value are set like this: $(<parametername>) to reflect current value of the variable
          # if you do/can not use a variable named like the parameter, just use the parameters as normal
          # resourceGroupName: '<Name of the ResourceGroup>'
          # azureSubscription: '<Name of the ARM-Service connection>'
          # location: '<location of the ResourceGroup>'

  - stage: mkdocs
    jobs:
      - template: azure-pipelines/jobs/mkdocs-material.yml
        parameters:
          mkdocsDeploy: ${{ variables.mkdocsDeploy }}
          # pythonVersion: '<Python Version to use when building MkDocs-Material>'
          # mkdocsSiteDir: '<folder to create the site by mkdocs>' - defaults to 'site'
