site_name: Azure-Pipelines with GitHub-Repo
site_url: https://mauwii.github.io/azure-pipelines-with-github-repo/
dev_addr: 127.0.0.1:8000
site_author: mauwii
site_description: >-
  ...to my playground, which was originally created to find out more about the
  possibilities when using GitHub-Repos  with Azure-DevOps to run YAML based
  Azure-Pipelines, as well as the differences compared to the use of Azure-Repos.
  Meanwhile I also begun using Jira to track Issues and Features and it's integrated
  Service-Desk to have a Place for Bug reports or feature suggestions. Feel free
  to compare it to the newly available GitHub Issue Templates, which imho are also
  a very good approach when you need to support your user base. I also started to
  play around with Jfrog's Artifactory which is a great option to find vulnerabilities
  or supply container images, to name just a few of it's features.

  So as u see, there is already a lot going on here and it's not getting boring at all

# Repository
repo_name: Mauwii/azure-pipelines-with-github-repo
repo_url: https://github.com/Mauwii/azure-pipelines-with-github-repo
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2022 Matthias Wild

# Configuration
theme:
  name: null
  custom_dir: 'src/mkdocs-material/material'

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    - toc.integrate
  palette:
    - media: '(prefers-color-scheme: light)'
      primary: blue
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: dark-blue
      accent: white
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: 'assets/favicon.png'
  icon:
    logo: 'material/library'
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Mauwii
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/mauwi
    - icon: material/email-fast
      link: mailto:mauwii@outlook.de

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 'Mauwii'
      repo: 'azure-pipelines-with-github-repo'
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

# Plugins
plugins:
  - search
  - git-revision-date
