parameters:
  - name: matrix
    type: object

strategy:
  matrix:
    ${{ parameters.matrix }}
  maxParallel: 3

steps:
  - template: steps/checkout_submodules.yml
    parameters:
      submodule: src/DevOpsBuildAgent
  - task: Docker@2
    displayName: dockerhub login
    inputs:
      containerRegistry: 'docker-mauwii'
      command: 'login'
  - bash: 'echo "##vso[task.setvariable variable=TAG]$(baseOS).$(baseDistro).$(baseVersion).$(baseArch).$(targetProc).dev"'
    displayName: 'set $(baseArch) tag'
  - script: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'
    displayName: 'qemu for $(baseArch)'
  - task: Docker@2
    displayName: 'build $(baseArch)'
    inputs:
      containerRegistry: 'docker-mauwii'
      repository: 'mauwii/devopsbuildagent'
      command: 'build'
      Dockerfile: 'src/DevOpsBuildAgent/Dockerfile'
      tags: '$(TAG)'
      arguments: '--build-arg "BASEARCH=$(baseArch)" --build-arg "targetproc=$(targetProc)"'
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-mauwii'
      repository: 'mauwii/devopsbuildagent'
      command: 'push'
      tags: '$(TAG)'
