parameters:
  - name: matrix
    type: object
  - name: maxParallelJobs
    type: number
jobs:
  - job:
    strategy:
      matrix: ${{ parameters.matrix }}
      maxParallel: ${{ parameters.maxParallelJobs }}
    steps:
      - template: steps/checkout_submodules.yml
        parameters:
          submodule: src/DevOpsBuildAgent
      - task: Docker@2
        displayName: docker login
        inputs:
          containerRegistry: 'docker-mauwii'
          command: 'login'
      - bash: 'echo "##vso[task.setvariable variable=TAG]$(baseOS).$(baseDistro).$(baseVersion).$(baseArch).${DEVTAG:-$(Build.BuildId)}"'
        displayName: 'set $(baseArch) tag'
        ${{ if not(eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
          env:
            DEVTAG: 'dev'
        ${{ if and(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
          env:
            DEVTAG: 'nightly'
      - bash: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'
        displayName: 'qemu for $(baseArch)'
      - task: Docker@2
        displayName: 'build $(baseArch)'
        inputs:
          containerRegistry: 'docker-mauwii'
          repository: 'mauwii/devopsbuildagent'
          command: 'build'
          Dockerfile: 'src/DevOpsBuildAgent/Dockerfile'
          tags: '$(TAG)'
          arguments: '--build-arg "BASEARCH=$(baseArch)" --build-arg "targetproc=$(targetProc)"'
      - task: Docker@2
        displayName: 'push $(baseArch)'
        inputs:
          containerRegistry: 'docker-mauwii'
          repository: 'mauwii/devopsbuildagent'
          command: 'push'
          tags: '$(TAG)'
