parameters:
  - name: pythonVersion
    displayName: Python Version to use when building MkDocs-Material
    type: string
  - name: mkdocsSiteDir
    displayName: Name of the Directory where MkDocs will be built to
    type: string
  - name: mkdocsDeploy
    displayName: When disabled MkDocs will only be built
    type: boolean

jobs:
  - job:
    displayName: MkDocs-Material
    steps:
      - template: steps/checkout_submodules.yml
        parameters:
          submodule: 'src/mkdocs-material'
          checkoutSelf: true

      - template: steps/build_mkdocs.yml
        parameters:
          pythonVersion: '${{ parameters.pythonVersion }}'
          mkdocsSiteDir: '${{ parameters.mkdocsSiteDir }}'

      - ${{ if eq(parameters.mkdocsDeploy, 'True') }}:
          - script: mkdocs gh-deploy --force --site-dir '${{ parameters.mkdocsSiteDir }}' --verbose
            displayName: deploy to GitHub-Pages
