parameters:
  - name: bicepDir
    displayName: Directory containing Folders with Bicep Templates
    type: string
    default: IaC/bicep/deploy
  - name: bicepParameter
    displayName: Used in some templates to change Resource Name or other variables
    type: string
    values:
      - dev
      - stg
      - prod
    default: dev
  - name: resourceGroupName
    displayName: Name of the Resource Group where templates will be deployed to
    type: string
    default: $(resourceGroupName)
  - name: azureSubscription
    displayName: Name of the ARM-Service Connection
    type: string
    default: $(azureSubscription)
  - name: location
    displayName: Location where the Resources will be deployed to
    type: string
    default: 'westeurope'
  - name: agentpool
    displayName: Agent-Pool to be used
    values:
      - 'Azure Pipelines'
      - 'local'
    default: 'Azure Pipelines'
  - name: cleanup
    type: boolean
    default: false

stages:
  - template: bicep_stage.yml
    parameters:
      bicepDir: ${{ parameters.bicepDir }}
      bicepParameter: ${{ parameters.bicepParameter }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      azureSubscription: ${{ parameters.azureSubscription }}
      location: ${{ parameters.location }}
      agentpool: ${{ parameters.agentpool }}

  - ${{ if eq(parameters.cleanup, 'True') }}:
      - template: cleanup.yml
        parameters:
          agentpool: ${{ parameters.agentpool }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
