parameters:
  - name: pythonVersion
    displayName: Python Version to use when building MkDocs-Material
    type: string
  - name: mkdocsSiteDir
    displayName: Name of the Directory where MkDocs will be built to
    type: string
  - name: mkdocsDeploy
    displayName: When disabled MkDocs will only be built
    type: boolean
  - name: vmImage
    displayName: Image the Build Agent should use
    type: string
    values:
      - 'ubuntu-latest'
      - 'macOS-latest'
      - 'windows-latest'

stages:
  - stage: mkdocs
    displayName: MkDocs-Material
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - template: jobs/mkdocs-material.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
          mkdocsSiteDir: ${{ parameters.mkdocsSiteDir }}
          mkdocsDeploy: ${{ parameters.mkdocsDeploy }}
