parameters:
  - name: pythonVersion
    displayName: Python Version to use when building MkDocs-Material
    type: string
  - name: mkdocsSiteDir
    displayName: Name of the Directory where MkDocs will be built to
    type: string
  - name: mkdocsDeploy
    displayName: When disabled MkDocs will only be built
    type: boolean
  - name: vmImage
    displayName: Image the Build Agent should use
    type: string
    values:
      - 'ubuntu-latest'
      - 'macOS-latest'
      - 'windows-latest'
  - name: agentpool
    displayName: Agent-Pool to be used
    values:
      - 'Azure Pipelines'
      - 'local'
    default: 'Azure Pipelines'

resources:
  containers:
    - container: ubuntu1804
      image: ubuntu:18.04

stages:
  - stage: mkdocs
    displayName: MkDocs-Material
    condition: succeeded()
    pool:
      name: ${{ parameters.agentpool }}
      ${{ if eq(parameters['agentpool'], 'Azure Pipelines') }}:
        vmImage: ${{ parameters.vmImage }}
        container: ubuntu1804
    jobs:
      - template: jobs/mkdocs-material.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
          mkdocsSiteDir: ${{ parameters.mkdocsSiteDir }}
          mkdocsDeploy: ${{ parameters.mkdocsDeploy }}
