parameters:
  - name: pythonVersion
    displayName: Python Version to use when building MkDocs-Material
    type: string
  - name: mkdocsSiteDir
    displayName: Name of the Directory where MkDocs will be built to
    type: string
  - name: mkdocsDeploy
    displayName: When disabled MkDocs will only be built
    type: boolean

stages:
  - stage: mkdocs
    displayName: MkDocs-Material
    pool:
      vmImage: $(vmImage)
    jobs:
      - template: jobs/mkdocs-material.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
          mkdocsSiteDir: ${{ parameters.mkdocsSiteDir }}
          mkdocsDeploy: ${{ parameters.mkdocsDeploy }}
