name: 'validate_pr.yml'

trigger: none

pr:
  autoCancel: false
  branches:
    include:
      - main
      - stable

variables:
  - template: variables/default.yml

stages:
  - template: main.yml
    parameters:
      mkdocsDeploy: ${{ false }}
      bicepParameter: ${{ variables['bicepParameter'] }}
