name: 'validate_pr.yml'

trigger: none

pr:
  autoCancel: false
  branches:
    include:
      - main
      - stable

variables:
  - template: variables/default.yml

extends:
  template: main.yml
  parameters:
    mkdocsDeploy: ${{ false }}
    bicepParameter: ${{ variables['bicepParameter'] }}
    cleanup: ${{ true }}
