parameters:
  - name: bicep_parameters_template
    type: object
    default:
      $schema: https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#
      contentVersion: '1.0.0.0'
      parameters:
        keyVaultName:
          value: mainkveu
        location:
          value: westeurope
        enabledForDeployment:
          value: false
        enabledForDiskEncryption:
          value: false
        enabledForTemplateDeployment:
          value: true
        tenantId:
          value: 77b36b7e-4568-4d4b-8c31-1346ca2dbf3d
        objectId:
          value: bb36fc31-5a0b-42db-8800-1a945c93eece
        keysPermissions:
          value: 
            - list
        secretsPermissions:
          value: 
            - list
        skuName:
          value: standard
        secretsObject:
          value:
            secrets:
              - secretName: firstSecretName
                secretValue: firstSecretValue
              - secretName: secondSecretName
                secretValue: secondSecretValue

steps:
- script: |
    echo "${JSON}" > main.parameters.$(bicepParameter).json
    ls -la
    cat main.parameters.$(bicepParameter).json
  workingDirectory: $(bicepDir)/$(bicepTemplateDir)
  displayName: Create Bicep Parameters
  env:
    JSON: ${{ convertToJson(parameters.bicep_parameters_template) }}
