name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
assignees:
  - mauwii
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: Jira_Issue
    attributes:
      label: Jira Issue
      description: If there is already a open issue in Jira, please enter the issue's ID surrounded in Brackets [], otherwise leave empty.
      placeholder: 'ex. [DG-42]'
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
  - type: input
    id: Failed_Runs
    attributes:
      label: Link to a failed run of the pipeline
      description: Please open a failed pipeline run, copy the URL and paste it here.
      placeholder: ex. https://dev.azure.com/mauwii/azure-pipelines-with-github-repo/_build/results?buildId=1337&view=results
    validations:
      required: true
