name: 🐞 Bug Report
description: File a bug report
title: '[bug]: '
labels: ['bug']
assignees:
  - mauwii
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: Jira_Issue
    attributes:
      label: Jira Issue
      description: If there is already a open issue in Jira, please enter the issue's ID surrounded in Brackets [], otherwise leave empty.
      placeholder: 'ex. [APWGR-42]'
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Briefly describe what happened and what you expected to happen.
      placeholder: Tell us what you see (like Step x throws error y). Also tell us what you expected to happen (like Step x should deploy template y to z)
    validations:
      required: true
  - type: input
    id: Failed_Runs
    attributes:
      label: Link to a failed run of the pipeline
      description: Please open a failed pipeline run, copy the URL and paste it here.
      placeholder: f.e. https://dev.azure.com/Mauwii/azure-pipelines-with-github-repo/_build/results?buildId=477&view=results
    validations:
      required: true
