parameters:
  - name: bicepDir
    type: string
    default: $(System.DefaultWorkingDirectory)

jobs:
  - job: createResourceGroup
    steps:
      - task: AzureCLI@2
        displayName: Create RG $(resourceGroupName)
        continueOnError: true
        inputs:
          azureSubscription: $(azureSubscription)
          workingDirectory: ${{ parameters.bicepDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az group create \
              --name $(resourceGroupName) \
              --location $(location)

  - job: lintBicep
    dependsOn: createResourceGroup
    displayName: Lint Bicep File
    continueOnError: false
    steps:
      - script: az bicep build --file main.bicep
        displayName: Run Bicep Linter
        name: LintBicepCode
        workingDirectory: ${{ parameters.bicepDir }}

  - job: validateBicepCode
    dependsOn: createResourceGroup
    condition: or(eq(variables.isStable, 'True'), eq(variables.isMain, 'True'))
    continueOnError: false
    displayName: Validate Bicep code
    steps:
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: $(azureSubscription)
          workingDirectory: ${{ parameters.bicepDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group validate \
              --resource-group $(resourceGroupName) \
              --template-file main.bicep \
              --parameters @main.parameters.$(sourceBranchName).json

  - job: previewAzureChanges
    dependsOn: createResourceGroup
    condition: or(eq(variables.isStable, 'True'), eq(variables.isMain, 'True'))
    displayName: Preview Azure changes
    continueOnError: false
    steps:
      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: $(azureSubscription)
          workingDirectory: ${{ parameters.bicepDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group what-if \
              --resource-group $(resourceGroupName) \
              --template-file main.bicep \
              --parameters @main.parameters.$(sourceBranchName).json

  - job: deployBicep
    dependsOn:
      - lintBicep
      - validateBicepCode
      - previewAzureChanges
    condition: and(succeeded(), or(eq(variables.isStable, 'True'), eq(variables.isMain, 'True')))
    steps:
      - template: steps/deploy_bicep.yml
        parameters:
          bicepParameters: ${{ parameters.bicepParameters }}
