parameters:
  - name: bicepDir
    type: string
    default: $(variables.bicepDir)
  - name: bicepTemplateDir
    type: string
    default: 'webApp-with-insights'
  - name: bicepParameter
    type: string
    default: dev
  - name: resourceGroupName
    type: string
    default: $(resourceGroupName)
  - name: azureSubscription
    type: string
    default: $(azureSubscription)
  - name: location
    type: string
    default: $(location)

jobs:
  - job: validateBicep
    displayName: validate Bicep
    continueOnError: false
    steps:
      - template: '../../${{ parameters.bicepDir }}/${{ parameters.bicepTemplateDir }}/main.parameters.yml'

      - script: az bicep build --file main.bicep
        displayName: Run Bicep Linter
        name: LintBicepCode
        workingDirectory: ${{ parameters.bicepDir }}/${{ parameters.bicepTemplateDir }}

      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          workingDirectory: ${{ parameters.bicepDir }}/${{ parameters.bicepTemplateDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group validate \
              --resource-group ${{ parameters.resourceGroupName }} \
              --template-file main.bicep \
              --parameters @main.parameters.${{parameters.bicepParameter}}.json

      - template: steps/create_resourceGroup.yml
        parameters:
          resourceGroupName: ${{ parameters.resourceGroupName }}
          azureSubscription: ${{ parameters.azureSubscription }}
          location: ${{ parameters.location }}

      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          workingDirectory: ${{ parameters.bicepDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group what-if \
              --resource-group ${{ parameters.resourceGroupName }} \
              --template-file main.bicep \
              --parameters @main.parameters.${{parameters.bicepParameter}}.json

  - job: deployBicep
    dependsOn: validateBicep
    condition: and(succeeded(), eq(variables.isPullRequest, 'False'), or(eq(variables.isMain, 'True'), eq(variables.isStable, 'True')))
    steps:
      - template: steps/deploy_bicep.yml
        parameters:
          bicepDir: ${{ parameters.bicepDir }}/${{ parameters.bicepTemplateDir }}
          bicepParameter: ${{ parameters.bicepParameter }}
