jobs:
  - job: lintBicep
    displayName: Lint Bicep File
    continueOnError: false
    steps:
      - script: az bicep build --file main.bicep
        displayName: Run Bicep Linter
        name: LintBicepCode

  - job: validateBicepCode
    continueOnError: false
    displayName: Validate Bicep code
    steps:
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group validate \
              --resource-group $(ResourceGroupName) \
              --template-file main.bicep \
              --parameters \
                secretKey=$(secretKey)
        env:
          secretKey: $(secretKey)

  - job: previewAzureChanges
    displayName: Preview Azure changes
    continueOnError: false
    steps:
      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group what-if \
              --resource-group $(ResourceGroupName) \
              --template-file main.bicep \
              --parameters \
                secretKey=$(secretKey)
        env:
          secretKey: $(secretKey)

  - job: deployBicep
    dependsOn:
      - lintBicep
      - validateBicepCode
      - previewAzureChanges
    condition: and(succeeded(), eq(variables.isStable, 'True'))
    steps:
      - template: steps/deploy_bicep.yml
