parameters:
  - name: bicepDir
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: resourceGroupName
    default: $(resourceGroupName)
    type: string
  - name: azureSubscription
    default: $(azureSubscription)
    type: string
  - name: location
    default: $(location)
    type: string

jobs:
  - job: createResourceGroup
    steps:
      - template: steps/create_resourceGroup.yml
        parameters:
          resourceGroupName: ${{ parameters.resourceGroupName }}
          azureSubscription: ${{ parameters.azureSubscription }}
          location: ${{ parameters.location }}

  - job: lintBicep
    dependsOn: createResourceGroup
    displayName: Lint Bicep File
    continueOnError: false
    steps:
      - script: az bicep build --file main.bicep
        displayName: Run Bicep Linter
        name: LintBicepCode
        workingDirectory: ${{ parameters.bicepDir }}

  - job: validateBicepCode
    dependsOn: createResourceGroup
    condition: or(eq(variables.isMain, 'True'), eq(variables.isStable, 'True'))
    continueOnError: false
    displayName: Validate Bicep code
    steps:
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          workingDirectory: ${{ parameters.bicepDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group validate \
              --resource-group ${{ parameters.resourceGroupName }} \
              --template-file main.bicep \
              --parameters @main.parameters.$(sourceBranchName).json

  - job: previewAzureChanges
    dependsOn: createResourceGroup
    condition: or(eq(variables.isMain, 'True'), eq(variables.isStable, 'True'))
    displayName: Preview Azure changes
    continueOnError: false
    steps:
      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          workingDirectory: ${{ parameters.bicepDir }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group what-if \
              --resource-group ${{ parameters.resourceGroupName }} \
              --template-file main.bicep \
              --parameters @main.parameters.$(sourceBranchName).json

  - job: deployBicep
    dependsOn:
      - lintBicep
      - validateBicepCode
      - previewAzureChanges
    condition: and(succeeded(), or(eq(variables.isMain, 'True'), eq(variables.isStable, 'True')))
    steps:
      - template: steps/deploy_bicep.yml
        parameters:
          bicepDir: ${{ parameters.bicepDir }}
