variables:
  pythonVersion: '3.9'
  vmImageName: ubuntu-latest
  resourceGroupName: azure-pipelines-with-github-repo
  projectName: apwgr
  location: westeurope
  azureSubscription: azure-mauwii
  mkdocsSiteDir: site
  mkdocsDeploy: ${{ False }}
  bicepParameter: dev
