variables:
  - name: pythonVersion
    value: '3.9'
    readonly: true
  - name: vmImageName
    value: 'ubuntu-latest'
    readonly: true
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
    readonly: true
  - name: location
    value: 'westeurope'
    readonly: true
  - name: azureSubscription
    value: 'azure-mauwii'
    readonly: true
  - ${{ if not(eq(variables['Build.SourceBranchName'], 'main')) }}:
    name: mkdocsDeploy
    value: ${{ True }}
