variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
  - name: pythonVersion
    value: '3.9'
  - name: environment
    value: dev
  - name: resourceGroupName
    value: azure-pipelines-with-github-repo
  - name: projectName
    value: apwgr
  - name: location
    value: westeurope
  - name: azureSubscription
    value: azure-mauwii
  - name: mkdocsSiteDir
    value: site
  - name: mkdocsDeploy
    value: ${{ false }}
  - name: bicepDir
    value: IaC/bicep/deploy
  - name: MaxConcurrency
    value: 1
  - name: bicepDeploy
    value: ${{ false }}
  # - name: vmImageName
  #   value: ubuntu-latest
  # - name: vmImage
  #   value: ${{ parameters.vmImage }}

parameters:
  - name: mkdocsDeploy
    displayName: Deploy MkDocs to GitHub-Pages
    type: boolean
    default: false
  - name: cleanup
    type: boolean
    default: false
