parameters:
  - name: matrix
    type: object
    default:
      - amd64:
        dockerdefaultplatformos: $(baseOS)
        dockerdefaultplatformarch: 'amd64'
        baseDistro: $(baseDistro)
        baseVersion: $(baseVersion)
        platformarch: 'x86_64'
        targetOS: $(baseOS)
        targetProc: 'x64'
      - arm64:
        dockerdefaultplatformos: $(baseOS)
        dockerdefaultplatformarch: 'arm64'
        baseDistro: $(baseDistro)
        baseVersion: $(baseVersion)
        platformarch: 'arm64'
        targetOS: $(baseOS)
        targetProc: 'x64'

steps:
  - ${{ each value in parameters.matrix }}:
      - task: Bash@3
        displayName: '${{ value.dockerdefaultplatformarch }} export'
        inputs:
          targetType: 'inline'
          script: 'export'
        env:
          dockerdefaultplatformos: ${{ value.dockerdefaultplatformos }}
          dockerdefaultplatformarch: ${{ value.dockerdefaultplatformarch }}
          platformarch: ${{ value.platformarch }}
          targetOS: ${{ value.targetOS }}
          targetproc: ${{ value.targetproc }}
      - script: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'
        displayName: 'qemu for ${{ value.dockerdefaultplatformarch }}'
      - task: Docker@2
        displayName: 'build ${{ value.dockerdefaultplatformarch }}'
        inputs:
          containerRegistry: 'docker-mauwii'
          repository: 'mauwii/devopsbuildagent'
          command: 'build'
          Dockerfile: 'src/DevOpsBuildAgent/Dockerfile'
          tags: '${{ value.dockerdefaultplatformos }}.${{ value.baseDistro }}.${{ value.baseVersion }}.${{ value.dockerdefaultplatformarch }}.${{ value.targetProc }}'
          arguments: '--build-arg platformarch="${{ value.dockerdefaultplatformarch }}" --build-arg targetarch="${{ value.targetOS }}-${{ value.targetProc }}"'
