parameters:
  - name: checkoutSelf
    displayName: Enable to checkout self repository first
    type: boolean
    default: true
  - name: submodule
    displayName: Submodule to update
    type: string
  - name: recursive
    displayName: Update submodule recursive
    type: boolean
    default: false
  - name: debug
    displayName: Enable Debug Output to list content of submodule-directories before and after update
    type: boolean
    default: false

steps:
  - ${{ if eq(parameters.checkoutSelf, true) }}:
      - checkout: self
        persistCredentials: true
        submodules: false
  - ${{ if eq(parameters.debug, true) }}:
      - script: ls -la ${{ parameters.submodule }}
        displayName: ls ${{ parameters.submodule }}
  - ${{ if eq(parameters.recursive, false) }}:
      - script: git submodule update --init ${{ parameters.submodule }}
        displayName: 'update submodule ${{ parameters.submodule }}'
  - ${{ if eq(parameters.recursive, true) }}:
      - script: git submodule update --init --recursive ${{ parameters.submodule }}
        displayName: 'update submodule ${{ parameters.submodule }} recursive'
  - ${{ if eq(parameters.debug, true) }}:
      - script: ls -la ${{ parameters.submodule }}
        displayName: ls ${{ parameters.submodule }}
