name: 'experimental'

trigger:
  branches:
    include:
      - feature/experimental/*

resources:
  repositories:
    - repository: DevOpsBuildAgent
      endpoint: Mauwii
      name: Mauwii/DevOpsBuildAgent
      trigger:
        - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: docker
    displayName: Docker
    dependsOn:
    jobs:
      - job: buildx64
        displayName: linux-x64
        dependsOn:
        steps:
          - script: Hello World!
