name: 'IaC-Trigger'

variables:
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'ARM-mauwii'

trigger:
  branches:
    include:
      - feature/*
      - main
  paths:
    include:
      - IaC/bicep

pool:
  vmImage: ubuntu-latest

parameters:
  - name: deploy
    type: string
    values:
      - acr
  - name: bicepPath
    type: string
    default: IaC/bicep
steps:
  - ${{ each value in parameters.deploy }}:
    - script: 'cat ${{ parameters.bicepPath }}/$(value)/main.bicep'
