name: 'IaC-Trigger'

variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
  - template: ../variables/default.yml
  - name: bicepDir
    value: IaC/bicep/deploy
  - name: bicepParameter
    value: dev
  - template: ../variables/default.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: ../variables/${{ variables['Build.SourceBranchName'] }}.yml
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stable') }}:
      - name: mkdocsDeploy
        value: ${{ True }}

trigger:
  branches:
    include:
      - feature/*
      - issue/*
      - refs/heads/main
      - refs/heads/stable
    exclude:
      - feature/experimental/*
  # paths:
  #   include:
  #     - IaC/bicep/deploy

pool:
  vmImage: ubuntu-latest

extends:
  template: ../bicep_stage.yml
  parameters:
    bicepDir: ${{ variables.bicepDir }}
    bicepTemplateDir:
      - 'acr'
      - 'kv'
    bicepParameter: ${{ variables.bicepParameter }}
