name: 'IaC-Trigger'

variables:
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'ARM-mauwii'
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
  - template: ../variables/default.yml
  - name: bicepDir
    value: IaC/bicep/deploy
  - name: bicepParameter
    value: dev

trigger:
  branches:
    include:
      - feature/*
  # paths:
  #   include:
  #     - IaC/bicep

pool:
  vmImage: ubuntu-latest

jobs:
  - template: ../jobs/bicep_jobs.yml
    parameters:
      bicepDir: ${{ variables.bicepDir }}
      bicepTemplateDir: 'acr'
      bicepParameter: ${{ variables.bicepParameter }}
