name: 'IaC-Trigger'

variables:
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'ARM-mauwii'

trigger:
  branches:
    include:
      - feature/*
      - main
  # paths:
  #   include:
  #     - IaC/bicep

pool:
  vmImage: ubuntu-latest

parameters:
  - name: deploy
    type: object
    default:
      - acr
      - kv
  - name: bicepPath
    type: string
    default: IaC/bicep/deploy

steps:
  - ${{ each value in parameters.deploy }}:
    - script: 'az bicep build --file ${{ parameters.bicepPath }}/${{ value }}/main.bicep'
    - template: ../../${{ parameters.bicepPath }}/${{ value }}/main.parameters.yml
