name: 'IaC-Trigger'

variables:
  - name: resourceGroupName
    value: 'azure-pipelines-with-github-repo'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'ARM-mauwii'
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
  - template: ../variables/default.yml
  - name: bicepDir
    value: IaC/bicep/deploy
  - name: bicepParameter
    value: dev

trigger:
  branches:
    include:
      - feature/*
  # paths:
  #   include:
  #     - IaC/bicep

pool:
  vmImage: ubuntu-latest

jobs:
  - job: getFolders
    steps:
      - powershell: |
          $folders = Get-ChildItem ${{ variables.bicepDir }} -Name
          Write-Host "##vso[task.setvariable variable=templateFolders;isoutput=true]$folders"
        name: getTemplateFolders
        displayName: Get Template Folders
  - job:
    dependsOn: getFolders
    variables:
      templateFolders: $[dependencies.getFolders.outputs['getTemplateFolders.templateFolders']]
    steps:
      - ${{ each value variables['templateFolders'] }}:
          - script: echo ${{value}}
      # - template: ../jobs/steps/bicep_steps.yml
      #   parameters:
      #     bicepDir: ${{ variables.bicepDir }}
      #     bicepTemplateDir: ${{ variables.templateFolders }}
      #     bicepParameter: ${{ variables.bicepParameter }}
  # - job:
  #   dependsOn: getFolders
  #   variables:
  #     templateFolders: $[dependencies.getFolders.outputs['passOutput.templateFolders']]
  #   steps:
  #     - script: 'echo "$(templateFolders)"'
  #     - ${{ each value in $(templateFolders) }}:
  #       - template: ../jobs/bicep_jobs.yml
  #         parameters:
  #           bicepDir: ${{ parameters.bicepDir }}
  #           bicepTemplateDir: $(templateFolders)
  #           bicepParameter: ${{ parameters.bicepParameter }}
