name: 'IaC-Trigger'

variables:
  isMain: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
  isStable: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
  isPullRequest: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  sourceBranchName: $[ variables['Build.SourceBranchName'] ]
  bicepDir: IaC/bicep/deploy
  bicepParameter: dev
  template: ../variables/default.yml
  ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
    template: ../variables/${{ variables['Build.SourceBranchName'] }}.yml
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/stable') }}:
    mkdocsDeploy: ${{ true }}

trigger:
  branches:
    include:
      - feature/*
      - issue/*
      - refs/heads/main
      - refs/heads/stable
    exclude:
      - feature/experimental/*
  # paths:
  #   include:
  #     - IaC/bicep/deploy

pool:
  vmImage: ubuntu-latest

extends:
  template: ../bicep_stage.yml
  parameters:
    bicepDir: ${{ variables.bicepDir }}
    bicepTemplateDir:
      - 'acr'
      - 'kv'
    bicepParameter: ${{ variables.bicepParameter }}
