trigger:
  batch: true
  branches:
    include:
      - feature/*
      - issue/*
  paths:
    include:
      - docs
      - mkdocs.yml
      - src/requirements-mkdocs-material.txt
      - azure-pipelines/mkdocs_stage.yml

pool:
  vmImage: ubuntu-latest

variables:
  - template: ../variables/default.yml

extends:
  template: ../mkdocs_stage.yml
  parameters:
    pythonVersion: ${{ variables.pythonVersion }}
    mkdocsSiteDir: ${{ variables.mkdocsSiteDir }}
    mkdocsDeploy: ${{ variables.mkdocsDeploy }}
