trigger: none

pr:
  autoCancel: false
  branches:
    include:
      - main
      - stable

variables:
  - template: ../variables/default.yml


pool:
  vmImage: $(vmImageName)

extends:
  template: ../main.yml
  parameters:
    mkdocsDeploy: ${{ variables['mkdocsDeploy'] }}
    bicepParameter: ${{ variables['bicepParameter'] }}
