parameters:
  - name: bicepParameter
    type: string
  - name: bicepDir
    type: string
    default: 'IaC/bicep/deploy'
  - name: bicepTemplateDir
    type: object

stages:
  - stage: bicep
    displayName: Bicep
    jobs:
      - ${{ each value in parameters.bicepTemplateDir }}:
          - template: jobs/bicep_jobs.yml
            parameters:
              bicepDir: ${{ parameters.bicepDir }}
              bicepTemplateDir: ${{ value }}
              bicepParameter: ${{ parameters.bicepParameter }}
              # The following parameters default value are set like this: $(<parametername>) to reflect current value of the variable
              # if you do/can not use a variable named like the parameter, just use the parameters as normal
              # resourceGroupName: '<Name of the ResourceGroup>'
              # azureSubscription: '<Name of the ARM-Service connection>'
              # location: '<location of the ResourceGroup>'
