parameters:
  - name: mngmtgrps
    displayName: Management Groups
    type: object
    default:
      - mngmtgrp001
      - mngmtgrp002

steps:
  - ${{ each mngmtgrp in parameters.mngmtgrps }}:
      - task: AzurePowerShell@5
        inputs:
          azureSubscription: '${{ mngmtgrp }}'
          ScriptType: 'FilePath'
          ScriptPath: '/scripts/cleanupautomation.ps1'
          azurePowerShellVersion: 'LatestVersion'
          pwsh: true
        env:
          ApplicationId: $(ApplicationId)
          ClientSecret: $(ClientSecret)
          TenantId: $(TenantId)
