trigger: none

pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily cleanup
    branches:
      include:
        - main

steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'mngmtgrp001'
      ScriptType: 'FilePath'
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true
      ScriptPath: 'scripts/cleanupautomation.ps1'
      ScriptArguments: -NewerResourceDays 7 -OlderResourceDays 14
    env:
      ApplicationId: $(ApplicationId)
      ClientSecret: $(ClientSecret)
      SpTenantId: $(TenantId)
