parameters:
  - name: mngmtgrps
    displayName: Management Groups
    type: object
    default:
      - mngmtgrp001
      - mngmtgrp002

steps:
  - ${{ each mngmtgrp in parameters.mngmtgrps }}:
      - task: AzurePowerShell@5
        inputs:
          azurePowerShellVersion: LatestVersion
          azureSubscription: ${{ mngmtgrp }}
          pwsh: true
          ScriptType: InlineScript
          Inline: |
            Get-AzResourceGroup
