# pipeline to test if things would work
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  vmImage: windows-2019

jobs:
  - job:
    steps:
      - task: PowerShell@2
        name: installPulumiCli
        displayName: install Pulumi-CLI
        inputs:
          targetType: inline
          script: |
            choco install pulumi
