name: 'experimental.yml'

trigger:
  batch: true
  branches:
    include:
      - feature/experimental/*

resources:
  repositories:
    - repository: DevOpsBuildAgent
      type: github
      name: Mauwii/DevOpsBuildAgent
      endpoint: Mauwii
      trigger:
        branches:
          include:
            - main

variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
  - template: variables/default.yml
  - template: variables/aci/devopsagent.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: variables/${{ variables['Build.SourceBranchName'] }}.yml
pool:
  vmImage: $(vmImageName)

stages:
  - stage: build
    displayName: Build Container
    jobs:
      - job:
        steps:
          - checkout: DevOpsBuildAgent
            path: src/Repo
            displayName: checkout DevOpsBuildAgent
            submodules: false
          - script: ls $(Build.Repository.LocalPath)/src/Repo
