# pipeline to test if things would work
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  vmImage: windows-2019

jobs:
  - job:
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.x  # Required  # Version range or exact version of a Python version to use, using semver's version range syntax. [More information](https://go.microsoft.com/fwlink/?LinkID=2006180)
          addToPath: true  # Required  # Whether to prepend the retrieved Python version to the PATH environment variable to make it available in subsequent tasks or scripts without using the output variable.
          architecture: x64 # Options: 'x86', 'x64' # Required  # The target architecture (x86, x64) of the Python interpreter.
      
      - task: PowerShell@2
        enabled: false
        name: installPulumiCli
        displayName: update Pulumi-CLI
        inputs:
          targetType: inline
          script: |
            # install Pulumi
            # choco install pulumi ## is already preinstalled
            # upgrade pulumi
            choco upgrade pulumi

      - task: PowerShell@2
        name: usePulumi
        displayName: Try to use Pulumi
        inputs:
          targetType: inline
          script: |
            # change directory to pulumi project
            cd IaC/pulumi/winquickstart
            # login to azure-cli
            az login -u "${env:PULUMIUSER}" -p "${env:PULUMIPASSWORD}" -t "${env:TENANTID}"
            # preview resources
            pulumi preview --stack dev --non-interactive
            # deploy resources
            pulumi up --yes
            # destroy them again
            pulumi destroy --yes
        env:
          TENANTID: $(TenantId)
          PULUMIUSER: $(PulumiUser)
          PULUMIPASSWORD: $(PulumiPassword)
          PULUMI_ACCESS_TOKEN: $(PulumiToken)
