# pipeline to test if things would work
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  vmImage: windows-2019

jobs:
  - job:
    steps:
      - task: PowerShell@2
        name: installPulumiCli
        displayName: update Pulumi-CLI
        inputs:
          targetType: inline
          script: |
            # install Pulumi
            # choco install pulumi ## is already preinstalled
            # upgrade pulumi
            choco upgrade pulumi

      - task: PowerShell@2
        name: usePulumi
        displayName: Try to use Pulumi
        inputs:
          targetType: inline
          workingDirectory: IaC/pulumi/winquickstart
          script: |
            # login to azure-cli
            az login -u "${env:PULUMIUSER}" -p "${env:PULUMIPASSWORD}" -t "${env:TENANTID}"
            # create venv
            # pulumi plugin install
            # list Child-Items to see where I am
            # Get-ChildItem ./venv/bin
            # activate venv
            # ./venv/bin/Activate.ps1
            # select stack
            pulumi stack select dev
            # preview resources
            pulumi preview
        env:
          TENANTID: $(TenantId)
          PULUMIUSER: $(PulumiUser)
          PULUMIPASSWORD: $(PulumiPassword)
          PULUMI_ACCESS_TOKEN: $(PulumiToken)
