name: 'experimental'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: docker
    displayName: Docker
    dependsOn:
    jobs:
      - job: build
        displayName: build and push
        steps:          
          - template: jobs/steps/checkout_submodules.yml
            parameters:
              submodule: devopsbuildagent

          - task: Docker@2
            displayName: login to dockerhub
            inputs:
              containerRegistry: 'docker-mauwii'
              command: 'login'

          - script: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            name: qemu
            displayName: register QEMU binary

          - task: Docker@2
            displayName: Build x64
            name: buildx64
            inputs:
              containerRegistry: 'docker-mauwii'
              repository: 'devopsbuildagent'
              command: 'build'
              Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)/**'
              tags: |
                latest
                linux-x64
                linux-x64-$(Build.BuildId)
              arguments: '--build-arg  BASE_IMAGE=amd64/ubuntu:18.04 TARGETARCH=linux-x64'

          - task: Docker@2
            displayName: build arm64
            name: buildarm64
            inputs:
              containerRegistry: 'docker-mauwii'
              repository: 'devopsbuildagent'
              command: 'build'
              Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)/**'
              tags: |
                linux-arm64
                linux-arm64-$(Build.BuildId)
              arguments: '--build-arg  BASE_IMAGE=arm64v8/ubuntu:18.04 TARGETARCH=linux-arm64'

          - task: Docker@2
            displayName: push to dockerhub
            inputs:
              containerRegistry: 'docker-mauwii'
              repository: 'devopsbuildagent'
              command: 'push'
              tags: |
                latest
                linux-x64
                linux-x64-$(Build.BuildId)
                linux-arm64
                linux-arm64-$(Build.BuildId)

          - script: |
              docker manifest create mauwii/devopsbuildagent:latest mauwii/devopsbuildagent:linux-x64 mauwii/devopsbuildagent:linux-arm64
              docker manifest annotate mauwii/devopsbuildagent:latest mauwii/devopsbuildagent:linux-x64 --os linux --arch amd64
              docker manifest annotate mauwii/devopsbuildagent:latest mauwii/devopsbuildagent:linux-arm64 --os linux --arch arm64 --variant v8
              docker manifest push --purge mauwii/devopsbuildagent:latest
            displayName: create and push manifest