# pipeline to test if things would work
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  vmImage: windows-2019

jobs:
  - job:
    steps:
      - task: PowerShell@2
        name: installPulumiCli
        displayName: install Pulumi-CLI
        inputs:
          targetType: inline
          script: |
            # install Pulumi
            choco install pulumi
            choco upgrade pulumi
            

      - task: PowerShell@2
        name: usePulumi
        displayName: Try to use Pulumi
        inputs:
          targetType: inline
          script: |
            # confirm Installation
            pulumi version
            # create and open quickstart folder
            mkdir quickstart
            cd quickstart
            # login to azure-cli
            az login -u ${env:PULUMIUSER} -p ${env:PULUMIPASSWORD} --tenant ${env:TENANTID}
            # start new pulumi project
            pulumi new azure-python --yes
        env:
          TENANTID: TenantId
          PULUMIUSER: PulumiUser
          PULUMIPASSWORD: PulumiPassword
          PULUMI_ACCESS_TOKEN: PulumiToken
