name: 'experimental.yml'

trigger:
  batch: true
  branches:
    include:
      - feature/experimental/*

variables:
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
  - template: variables/default.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: variables/${{ variables['Build.SourceBranchName'] }}.yml
pool:
  vmImage: $(vmImageName)

stages:
  - stage: bicep
    displayName: Bicep
    jobs:
      - template: containerinstance.yml
        parameters:
          containerinstance: devopsagent
