trigger:
  branches:
    include:
      - feature/experimental/*

variables:
  - template: ../variables/default.yml
  - template: ../variables/aci/devopsagent.yml
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/stable') }}:
      - template: ../variables/${{ variables['Build.SourceBranchName'] }}.yml

resources:
  repositories:
    - repository: devopsagent
      endpoint: Mauwii
      name: Mauwii/DevOpsBuildAgent
      trigger:
        - main

pool:
  name: 'Azure Pipelines'
  # vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build Container
    jobs:
      - job: matrix
        strategy:
          matrix:
