# pipeline to test if things would work
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  vmImage: windows-2019

jobs:
  - job:
    steps:
      - task: PowerShell@2
        enabled: false
        name: installPulumiCli
        displayName: install Pulumi-CLI
        inputs:
          targetType: inline
          script: |
            # install Pulumi
            # choco install pulumi ## is already preinstalled
            choco upgrade pulumi

      - task: PowerShell@2
        name: usePulumi
        displayName: Try to use Pulumi
        inputs:
          targetType: inline
          workingDirectory: IaC/pulumi/winquickstart
          script: |
            # login to azure-cli
            az login -u "${env:PULUMIUSER}" -p "${env:PULUMIPASSWORD}" -t "${env:TENANTID}"
            # create venv
            pulumi plugin install
            # create resources
            pulumi up --yes
            # delete them again
            pulumi destroy --yes
        env:
          TENANTID: $(TenantId)
          PULUMIUSER: $(PulumiUser)
          PULUMIPASSWORD: $(PulumiPassword)
          PULUMI_ACCESS_TOKEN: $(PulumiToken)
