trigger:
  batch: true
  branches:
    include:
      - feature/*
      - issue/*
      - update/*
  paths:
    include:
      - IaC/bicep/deploy
      - azure-pipelines/iac-bicep.yml
      - azure-pipelines/stages/bicep_stage.yml
      - azure-pipelines/stages/jobs/steps/bicep_steps.yml
      - scripts/New-BicepMatrix.ps1

pr: none

variables:
  - template: variables/default.yml

stages:
  - template: stages/bicep_stage.yml
    parameters:
      bicepDir: '${{ variables.bicepDir }}'
      bicepParameter: '${{ variables.environment }}'
      resourceGroupName: '${{ variables.resourceGroupName }}'
      azureSubscription: '${{ variables.azureSubscription }}'
      location: '${{ variables.location }}'
