trigger:
  batch: true
  branches:
    include:
      - feature/*
      - issue/*
  paths:
    include:
      - IaC/bicep/deploy
      - azure-pipelines/triggers/iac-bicep.yml

pr: none

variables:
  - template: variables/default.yml

pool:
  vmImage: 'ubuntu-18.04'

extends:
  template: stages/bicep_stage.yml
  parameters:
    bicepDir: '${{ variables.bicepDir }}'
    bicepParameter: '${{ variables.environment }}'
    resourceGroupName: '${{ variables.resourceGroupName }}'
    azureSubscription: '${{ variables.azureSubscription }}'
    location: '${{ variables.location }}'
