# was created to see if local Agent is reachable and working
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  name: local

stages:
  - stage:
    jobs:
      - job:
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
              addToPath: true
              architecture: 'x64'
          - script: 'python3 --version'
          - task: AzureCLI@2
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: 'az resource list'
              azureSubscription: azure-mauwii
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'azure-mauwii'
              ScriptType: 'InlineScript'
              Inline: 'Get-AzContext'
              errorActionPreference: 'continue'
              azurePowerShellVersion: 'LatestVersion'
