# was created to see if local Agent is reachable and working
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  name: local

stages:
  - stage:
    jobs:
      - job:
        steps:
          - task: AzureCLI@2
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: 'az resource list'
              azureSubscription: azure-mauwii

