# was created to see if local Agent is reachable and working
trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  name: local

stages:
  - stage:
    jobs:
      - job:
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'export'
