parameters:
  - name: pythonVersion
    displayName: Python Version to use when building MkDocs-Material
    type: string
    default: $(pythonVersion)
  - name: mkdocsSiteDir
    displayName: Name of the Directory where MkDocs will be built to
    type: string
    default: 'site'
  - name: mkdocsDeploy
    displayName: When disabled MkDocs will only be built
    type: boolean
    default: false

stages:
  - stage: mkdocs
    displayName: MkDocs
    jobs:
      - template: jobs/mkdocs-material.yml
        parameters:
          mkdocsDeploy: ${{ parameters.mkdocsDeploy }}
          # pythonVersion: '<Python Version to use when building MkDocs-Material>'
          # mkdocsSiteDir: '<folder to create the site by mkdocs>' - defaults to 'site'
