trigger: none

pr:
  autoCancel: false
  branches:
    include:
      - main
      - stable

variables:
  - template: variables/default.yml

pool:
  vmImage: $(vmImageName)

extends:
  template: stages/main.yml
  parameters:
    bicepDir: '${{ variables.bicepDir }}'
    bicepParameter: '${{ variables.environment }}'
    resourceGroupName: '${{ variables.resourceGroupName }}'
    azureSubscription: '${{ variables.azureSubscription }}'
    location: '${{ variables.location }}'
    mkdocsDeploy: false
    vmImage: 'ubuntu-latest'
